# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alamat', models.CharField(max_length=50)),
                ('kode_post', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kota', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='detailkota',
            name='kota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Kota'),
        ),
    ]
