# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('insurance_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDeliveryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.IntegerField(default=0)),
                ('member_price', models.IntegerField(default=0)),
                ('companydelivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CompanyDelivery')),
                ('fr_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_fr_city_list_kota', to='booking.Kota')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_to_city_list_kota', to='booking.Kota')),
            ],
        ),
    ]
