# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_companydelivery_companydeliveryprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydelivery',
            old_name='insurance_price',
            new_name='price_insurance',
        ),
    ]
