# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20151228_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydelivery',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companydelivery',
            name='toc_insurance',
            field=models.TextField(default=datetime.time),
        ),
    ]
